version: '3'
services:
  weatherbackend:
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - weather

  weatherfrontend:
    build: ./weather
    ports:
      - "3000:3000"
    networks:
      - weather
    environment:
      - REACT_APP_API_URL=http://weatherbackend:8080
    depends_on:
      - weatherbackend

networks:
  weather:
    driver: bridge
